sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - mvn clean install
  - cd application
  - docker build -t spidergawd/continuous-integration .

script:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push spidergawd/continuous-integration
